# @package _global_
defaults:
  - project: default_project
  - data: sql_full
  - preprocessing: default_preprocessing
  - training: default_training
  - evaluation: default_evaluation
  - sweeper: optuna_multithread