
data:
  n_training_samples: Null  # Number of training samples to use, defaults to None in which cases it uses all samples.
  lookahead_days: 1826.25 # (float): Number of days from prediction time to look ahead for the outcome.
  pred_col_name_prefix: "pred_" # (str): prefix of predictor columns
