post_processing:
  n_to_load: 50000000
  impute_all: False
  force_all_binary: False
  train:
    drop_if_any_diabetes_before_date: Null
    min_lookahead_days: 0 # Drop all prediction times where (max timestamp in the dataset) - (current timestamp) is less than min_lookahead_days
    min_lookbehind_days: 0 # Drop all prediction times where (current timestamp) - (min timestamp in the dataset) is less than min_lookbehind_days
  val:
    drop_if_any_diabetes_before_date: Null
    min_lookahead_days: 0 # Drop all prediction times where (max timestamp in the dataset) - (current timestamp) is less than min_lookahead_days
    min_lookbehind_days: 0 # Drop all prediction times where (current timestamp) - (min timestamp in the dataset) is less than min_lookbehind_days
  washin_days: 0

training:
  lookahead_days: 1826.25 # The furthest interval the model looks ahead from prediction time
  lookbehind_days: 9999 # How far the model looks behind from prediction time
  cols_to_drop_before_training: [dw_ek_borger, prediction_time_uuid]

evaluation:
  wandb: False
